✨ Added graphql-ws
graphql-editor/graphql-zeus pull request #301
Opened 2022-06-07 15:12 UTC by GauBen

Working to fix #288

- [x] Added [graphql-ws](https://github.com/enisdenjo/graphql-ws)
- [x] Preserve the current behavior (named *legacy*, because non-standard)
- [x] Implement `open` and `off`, if they still make sense
- [x] Write the documentation
- [x] Add graphql-ws as an optional peer dependency

2022-06-20 06:36 UTC, LMaxence commented
Hello @aexol, could you update us on the status of this please ? There are no review, no feedbacks, and it is hard for us to know if we can expect this feature that we really really really need merged at some point or if we have to fork the project on our side.

2022-06-20 13:31 UTC, aexol commented
Sorry I thought it is not completed. Why not make a plugin instead of forcing graphql-ws to the main code?

2022-06-21 07:49 UTC, GauBen commented
It looks like Zeus support subscriptions out of the box but that's not the case because the implementation of [apiSubscription](https://github.com/graphql-editor/graphql-zeus/blob/master/src/TreeToTS/functions/new/apiSubscription.ts#L3) is non standard. This PR is more of a fix to add the standard implementation to the core, as a non-default feature flag to keep the current behavior, rather a new feature. This PR will make Zeus compatible with Apollo and Yoga subscriptions that both follow [this standard](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md).

I haven't written the documentation yet because I wanted to make sure that you were okay with changes to the core. If you agree on this design, I'll complete the todo list.

Also, I chose to implement it as a non-breaking change; both the current implementation and graphql-ws currently coexist in generated.ts: https://github.com/graphql-editor/graphql-zeus/pull/301/files#diff-96a2264dfde03a31fbad8f2aac04c691dd6a7291919fbcbf258ba30782f394daR664

Then, you may or may not make graphql-ws the default in the next major version.

2022-06-21 09:54 UTC, GauBen commented
> If it won't break I am ok go ahead and finish it. 

Great news! I'll try to have it ready by the end of the week.

> you are implementing ts with strings

Not really, I did it the same way as you:
- Created a TS file in `src/TreeToTS/functions/apiSubscription/graphql-ws.ts`
- Added a bit of magic to `src/CLI/libBuilder.ts` to handle the new files

2022-06-27 12:41 UTC, GauBen commented
Ready for review!

I feel like a lot of things are wrong:

### The type `SubscriptionToGraphQL` is not correctly implemented

In the current implementation, this is the `open` function:
```ts
return {
    // ...
	open: (e: () => void) => {
		ws.onopen = e;
	}
}
```

[link](https://github.com/graphql-editor/graphql-zeus/blob/59d55d8d0d71b315b97a01f4a1591b26d305727c/src/TreeToTS/functions/new/apiSubscription.ts#L27-L29)

And this is the signature:

```ts
export type SubscriptionToGraphQL<Z, T, SCLR extends ScalarDefinition> = {
  // ...
  open: () => void;
};
```

[link](https://github.com/graphql-editor/graphql-zeus/blob/59d55d8d0d71b315b97a01f4a1591b26d305727c/src/TreeToTS/functions/new/types.ts#L75)

### I committed documentation artifacts

Is this ok?

### There is no way to properly cleanup

I implemented the cleanup function with a Proxy over `ws.close`, but it feels dirty. Graphql-ws offers a proper way to unsubscribe and clean up:

https://github.com/enisdenjo/graphql-ws/blob/77682cd3d9bac748b5b24e2f8cf88e1d98c7a448/src/client.ts#L434-L442

### We should abstract the underlying transport

There are two competing standards, graphql-ws and graphql-sse, who share the exact same interface. We might be interested in moving from concrete APIs (`ws`, `open`...) to more abstract ones (`transport`, `cleanup`...), in order to make Zeus implementation-agnostic.

2022-07-01 21:27 UTC, aexol commented
Thanks @GauBen I'll try to review next days

2022-07-04 07:25 UTC, GauBen commented
Thank you! I'll sort the merge commits out soon.

2022-07-04 20:47 UTC, aexol commented on package.json
> +    "graphql-wq": ">=5"
should be graphql-ws

2022-07-04 20:51 UTC, aexol commented on src/TreeToTS/functions/apiSubscription/graphql-ws.ts
> +import { createClient, type Sink } from 'graphql-ws'; // keep
ok

2022-07-04 20:52 UTC, aexol commented on src/TreeToTS/index.ts
> +  subscriptions: 'legacy' | 'graphql-ws';
just make optional with default value for better backwards compatibility

2022-07-04 20:52 UTC, aexol commented on src/TreeToTS/index.ts
> +  static resolveTreeSplit({ tree, env = 'browser', host, esModule, headers, subscriptions }: ResolveOptions) {
provide a default 'legacy' value

2022-07-04 20:53 UTC, aexol requested changes
Looks nice! Please fix those small errors and suggestions, so we can merge and release next version 🚀

2022-07-08 08:45 UTC, merged

2022-07-08 09:24 UTC, GauBen commented
🎉

2022-07-08 10:08 UTC, aexol commented
Please test `5.1.7` when ready :)

2022-07-08 10:08 UTC, aexol commented
Thank you!

2022-07-11 13:14 UTC, GauBen commented
Everything works on my side! 🎉